### ISSUE TITLE
some trouble getting it to work

### ISSUE THREAD

**Issue by aleqx** [TradeFace/tuyamqtt#1]
Continuing from here: https://github.com/mileperhour/localtuya-homeassistant/issues/8#issuecomment-583602884

Maybe a complete MWE would help. Here's what I tried so far on a RPi 3B running Raspbian 10. 
- installed `mosquitto` and it's listening on port 1823 (no auth). 
- changed your config file to connect to 127.0.0.1 port 1823
- pip installed bitstring and paho_mqtt
- started your stuff with `python3 -u main.py` which said `MQTT Connection state: Connection successful for tuya`
- installed `mosquitto-clients` and wanted to first check that I can see/control the smartplug from the cli, so I tried `mosquitto_sub -v -t tuya/3.3/55327730840d8e51..../4e7798d24b9c..../192.168.1.43/1/attributes` and tried switching the smartplug on and off which should generate some messages, but I get nothing

I then also tried the following:
- `mosquitto_pub -t tuya/3.3/55327730840d8e51..../4e7798d24b9c..../192.168.1.43/1/command -m ON`
- your server outputs:
```
MQTT Connection state: Connection successful for tuya
message received ON topic tuya/3.3/55327730840d8e51..../4e7798d24b9c..../192.168.1.43/1/command retained 0
MQTT Connection state: Connection successful for tuya/3.3/55327730840d8e5116d6/4e7798d24b9cf02f/192.168.1.43
Data must be aligned to block boundary in ECB mode status for tuya/3.3/55327730840d8e5116d6/4e7798d24b9cf02f/192.168.1.43
Data must be aligned to block boundary in ECB mode status for tuya/3.3/55327730840d8e5116d6/4e7798d24b9cf02f/192.168.1.43
<keeps repeating>
```

Does that mean the device is not compatible with tuya protocol v3.3?

**Comment by TradeFace** [comment]
@aleqx, it is trying to decrypt a reply from the tuya device. It could very well be that the device has older firmware. I rewrote python-tuya, but had no way of testing older firmware devices, so I left it out ( mines are all protocol 3.3) I can but it back in the beginning of next week in if you can test it.

**Comment by aleqx** [comment]
Still a little confused: With mosquitto running, what should I subscribe to with mosquitto_sub and what should I publish to with mosquit_pub in order to see the energy values that are normally under dps[1]?

Is it these?

`mosquitto_sub -v -t tuya/3.3/55327730840d8e51..../4e7798d24b9c..../192.168.1.43/1/attributes`

`mosquitto_pub -v -t tuya/3.3/55327730840d8e51..../4e7798d24b9c..../192.168.1.43/1/command -m ON`

Also, I did change the host in tuyamqtt.conf from 192.168.1.14 to 127.0.0.1 but then after starting `python -m main.py` and looking at the generated tuyamqtt.db I see these:
```
INSERT INTO settings VALUES(1,'mqtt_host','192.168.1.14');
INSERT INTO settings VALUES(2,'mqtt_port','1883');
```
What gives?

**Comment by TradeFace** [comment]
I think you can subscribe to a wildcard 
```
tuya/3.3/55327730840d8e51..../4e7798d24b9c..../192.168.1.43/*
``` 
The pub command is Okay

The settings table is for future use. It should be in a dev branch... ;-)

**Comment by aleqx** [comment]
Nothing get to the subscriber, presumably because your server can't decode it in order to send it to the mqtt server. Looking forward to test it after you put the code for v3.1 back -- just drop a message here when you get the chance.

Out of curiosity - was the v3.1 code that you removed only affecting the generation of the payload? I was looking here https://github.com/TradeFace/python-tuya/blob/7f8180e6cebe28c9b5448a70164ce3c2636ee8c4/pytuya/__init__.py#L282

**Comment by aleqx** [comment]
Wondering if you had a chance to look at the v3.1 code?

**Comment by TradeFace** [comment]
Hi, no sorry.... I am extremely busy these days. Maybe this weekend, but no promises

**Comment by TradeFace** [comment]
I put back some code to support 3.1 devices. I have no way of testing this. Can you guys have a look? (you'll need to upgrade https://github.com/TradeFace/tuya to version 1.0.3 (current master)
