### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by codeclinic** [TradeFace/tuyamqtt#11]
I've installed this as using the standard python method, and everything appears to have installed ok. However, I can't get it to run. `sudo systemctl status tuyamqtt` give the following output:

`● tuyamqtt.service - Tuya MQTT
   Loaded: loaded (/etc/systemd/system/tuyamqtt.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-05-03 22:46:43 CEST; 17s ago
  Process: 7706 ExecStart=/usr/bin/python3 -u main.py (code=exited, status=2)
 Main PID: 7706 (code=exited, status=2)

May 03 22:46:43 ha-server systemd[1]: tuyamqtt.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 03 22:46:43 ha-server systemd[1]: tuyamqtt.service: Failed with result 'exit-code'.
May 03 22:46:43 ha-server systemd[1]: tuyamqtt.service: Service RestartSec=100ms expired, scheduling restart.
May 03 22:46:43 ha-server systemd[1]: tuyamqtt.service: Scheduled restart job, restart counter is at 5.
May 03 22:46:43 ha-server systemd[1]: Stopped Tuya MQTT.
May 03 22:46:43 ha-server systemd[1]: tuyamqtt.service: Start request repeated too quickly.
May 03 22:46:43 ha-server systemd[1]: tuyamqtt.service: Failed with result 'exit-code'.
May 03 22:46:43 ha-server systemd[1]: Failed to start Tuya MQTT.
`

Any ideas as to what I can try to resolve this?

Thanks.

**Comment by TradeFace** [comment]
DId you update /etc/tuyamqtt.conf with your setttings?

**Comment by codeclinic** [comment]
yes.

**Comment by TradeFace** [comment]
Okay, what output do you get when you run `/usr/bin/python3 -u main.py -vvv` in the tuyamqtt directory?

**Comment by codeclinic** [comment]
`setting debug to: -vvv
MQTT Connection state: Connection successful for tuya
`

**Comment by TradeFace** [comment]
The code seems to run fine on it self, but it apparently doesn't wants to run as a service.  I am not sure what causes the problem. It complains about INVALIDARGUMENT. Maybe you can tweak a bit with that?

**Comment by codeclinic** [comment]
I can see the invalid argument, but no idea what that refers to, but have no idea what that relates to.

**Comment by codeclinic** [comment]
So, `sudo journalctl -u tuyamqtt` is showed that the service couldn't open the main.py file. 

I've added the WorkingDirectory location to the unit file and it's working now.

**Comment by TradeFace** [comment]
Okay, but wasn't that set? When you run `make install` it should set the workdir path

**Comment by codeclinic** [comment]
No, that's why I had to add it.

**Comment by TradeFace** [comment]
That could be the case, indeed. Maybe some checks should be added.
