### ISSUE TITLE
How to get dps status?

### ISSUE THREAD

**Issue by Regaddi** [TradeFace/tuyamqtt#2]
Hey!

I've been able to setup tuyamqtt on my Raspberry PI and it successfully connected to my plug and I'm able to switch it on and off :+1:

However I decided to give this a try as I want to actively read some dps values on an interval basis and I'm struggling to find the right MQTT command to do that.
In the README you mention different topics to deal with, but I don't seem to be able to grasp the right message, topic and payload to trigger a "read state for dps".

Could you help me finding the right command?

I assume I'll just have to set the right payload for `tuya/3.3/{deviceId}/{deviceKey}/{deviceIp}/attributes`, but what payload do I need?
You mentioned in https://github.com/codetheweb/tuyapi/issues/246#issuecomment-569427352 that it should be good to set a JSON payload with `null` values for the dps keys I want to read.

But this throws an error: `Object of type bytes is not JSON serializable set_status`

I'm using nodered to trigger the actions.

Thanks!

**Comment by Regaddi** [comment]
@TradeFace Any chance you could have a look into this?

**Comment by TradeFace** [comment]
You don't actively pull a state from tuyamqtt. It polls the status from the device(s) every `entity['status_poll']` seconds. (see line 197);  which is hardcoded for the moment at 5 seconds ( see line 302). When there is a status change it is published to the mqtt-broker. 

If you are able to switch the device, tuyamqtt "knows" it and should automatically publish the attributes to your broker. (see line 137)

hth

**Comment by Regaddi** [comment]
So I can see in my node-red debug logs, that the device itself sends a message every 5 seconds, when tuyamqtt is running. But I don't get any message from my `mqtt in` node.
I'm using the [node-red-tuya-local](https://github.com/subzero79/node-red-contrib-tuya-local), but this sends `dps.1` only most of the time. One hour per day I also get `dps.18` and `dps.19` which contains the current power and ampère information (this is what I'm interested in).

Do you know if it's even possible to force retrieve these values through the tuya package?
As far as I understand from reading the code it highly depends on the data the device itself returns and it doesn't seem very straightforward to do so.

I've got a Teckin SP22 with tuya 3.3 firmware on it, that's why I hoped tuyamqtt would finally help me retrieving the data I want 😄

**Comment by TradeFace** [comment]
tuyamqtt doesn't have any knowledge of devices, indeed. In that way it tries to act like some kind of proxy. In https://github.com/TradeFace/tuya I abstracted away some of the internals to get the status, because not all devices behave nicely. There are a few commands that could result in a status reply of the device. Perhaps your device needs an other command to trigger the status reply.

**Comment by TradeFace** [comment]
I guess this is solved...
