### ISSUE TITLE
Ctrl+C does not stop server

### ISSUE THREAD

**Issue by Regaddi** [TradeFace/tuyamqtt#3]
When the server is connected with at least 1 device and has a thread running, Ctrl+C won't stop it.
You'll have to call Ctrl+C another time.
I assume the first Ctrl+C only stops the thread, but not the main process.

```
MQTT Connection state: Connection successful for tuya
^CCtrl C - Stopping server
^[[A^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

**Comment by TradeFace** [comment]
Probably the other way around, the main thread stays in the foreground but doesn't have code to send the kill signal to the active threads.
