### ISSUE TITLE
How to set up dimmer brightness?

### ISSUE THREAD

**Issue by tjonaitis** [TradeFace/tuyamqtt#4]
Hi,

So I was able to connect my dimmer with tuyamqtt and simple ON/OFF works as it should! I was wondering would it be possible to change brightness for my dimmer? I can tell that second dps is my dimmer's brightness, please see the json:
`{
	"dps": {
		"1": false,
		"2": 996,
		"3": 24
	},
	"via": {
		"1": "mqtt",
		"2": "tuya",
		"3": "tuya"
	},
	"time": 1585077429.6966279
}`

**Comment by TradeFace** [comment]
On line 96 it says `self.set_status(dps_key, payload_bool(message.payload))`. Which converts any incoming value to a boolean, if possible. Otherwise it will return the original value. So in theory you should be able to set the dimmer value. I haven't tested it though

**Comment by tjonaitis** [comment]
Ok, so how should my topic and payload look like? Instead of using dps 1 I should swap it with dps 2 and send the brightness value as a payload, please see the example:
  
`command_topic: "tuya/3.3/device_id/local_key/device_ip/2/command"`
`payload: 255`

**Comment by TradeFace** [comment]
Yeah, I guess that should do the trick.

**Comment by TradeFace** [comment]
I guess this is solved...
