### ISSUE TITLE
Fix exit

### ISSUE THREAD

**Issue by emontnemery** [TradeFace/tuyamqtt#54]
Tuyamqtt should shut down all threads:
- Its own worker thread
- Its own MQTT client
- All TuyaMQTT entities, including MQTT client and TuyaClient

**Comment by emontnemery** [comment]
@TradeFace Are you working on this already, if not I'll give it a go :)

**Comment by TradeFace** [comment]
I've added a thread stop to TuyaMQTTEntity in #33. That seemed to get rid of the worst errors. I am sure there is lots of room for improvement.

**Comment by emontnemery** [comment]
Yeah, I saw that, but there are a few more things to do.

**Comment by TradeFace** [comment]
@emontnemery Can I close this?

**Comment by emontnemery** [comment]
Yes, I think so.
